### ISSUE TITLE
DA期货这边支持linux，请问一下vnpy这边可以帮忙支持da api的linux版本么？或者有计划么？

### ISSUE THREAD

**Issue by Deanzou** [vnpy/vnpy_da#11]

**Comment by Deanzou** [comment]
<img width="414" alt="image" src="https://github.com/vnpy/vnpy_da/assets/1018936/1a5b291c-4f9f-457c-9969-7169f58503be">

**Comment by vnpy** [comment]
技术上可以实现，但是去年因为直达期货缩减IT技术团队，目前社区在直达的实盘客户不多，所以这块的开发优先级可能较低，或者如果有什么原因必须使用直达欢迎联系官方团队沟通

**Comment by Deanzou** [comment]
感谢 回复

**Comment by Deanzou** [comment]
请问一下 现阶段 交易恒生指数期货 用的比较多的而且交易费用比较低的 一般使用什么方案？ 能给点意见么？ 哈哈  感谢🙏

**Comment by vnpy** [comment]
外盘期货目前比较主流的两个选择是易盛（TAP和Esunny，速度较快）和盈透（IB，全球市场接入）

**Comment by Deanzou** [comment]
多谢答复 十分感谢 🙏
